version: "3.8"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bank
    ports:
      - "3306:3306"
    container_name: mysql-container
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - jenkins

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    container_name: redis-container
    networks:
      - jenkins

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    user: root
    ports:
      - "8081:8080"       # bạn đã viết ngược
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: anhnt10/transfer-money-ci-cd:latest
    container_name: transfer-container
    ports:
      - "8080:8080"
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: bank
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - jenkins

volumes:
  jenkins_home:

networks:
  jenkins:
    external: false
